package work.wengyuxian.util;

import java.util.HashSet;

public class Alpahas {

    // 字母表
    public static HashSet<Character> alpahas = new HashSet<Character>() {
        {
            add('0');
            add('1');
            add('2');
            add('3');
            add('4');
            add('5');
            add('6');
            add('7');
            add('8');
            add('9');
            add('a');
            add('b');
            add('c');
            add('d');
            add('e');
            add('d');
            add('f');
            add('g');
            add('h');
            add('i');
            add('j');
            add('k');
            add('l');
            add('m');
            add('n');
            add('o');
            add('p');
            add('q');
            add('r');
            add('s');
            add('t');
            add('u');
            add('v');
            add('w');
            add('x');
            add('y');
            add('z');
            add('A');
            add('B');
            add('C');
            add('D');
            add('E');
            add('F');
            add('G');
            add('H');
            add('I');
            add('J');
            add('K');
            add('L');
            add('M');
            add('N');
            add('O');
            add('P');
            add('Q');
            add('R');
            add('S');
            add('T');
            add('U');
            add('V');
            add('W');
            add('X');
            add('Y');
            add('Z');
            add('_');
            add('.');
            add('+');
            add('-');
            add('*');
            add('/');
            add('&');
            add('!');
            add('\\');
            add('(');
            add(')');
            add('[');
            add(']');
            add('{');
            add('}');
        }
    };
}